version: "3.8"
services:
    cantaloupe:
    image: edirom/cantaloupe
    volumes:
      - ./data/images:/var/lib/cantaloupe/images
      - ./cantaloupe/cantaloupe.properties:/etc/cantaloupe.properties
    ports:
      - "8182:8182"
    environment:
      CANTALOUPE_CONFIG: /etc/cantaloupe.properties
      JAVA_OPTS: "-Xms512m -Xmx2g"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8182/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/volumes/db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: ./django
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app
      - ./docker/volume/data:/app/data/images
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

volumes:
  db_data:
  data:
