# Generated by Django 5.0.7 on 2024-07-25 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationPage',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='AnnotationPage', max_length=50)),
                ('items', models.ManyToManyField(related_name='annotation_page_items', to='app.annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('annotation_pages', models.ManyToManyField(related_name='canvas_items', to='app.annotationpage')),
                ('painting_annotations', models.ManyToManyField(related_name='canvas_painting_annotations', to='app.annotation')),
                ('label', models.ManyToManyField(related_name='canvas_labels', to='app.label')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_annotations', to='app.canvas'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations_as_body', to='app.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.ManyToManyField(related_name='image_labels', to='app.label'),
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.URLField(default='http://iiif.io/api/presentation/3/context.json')),
                ('label', models.ManyToManyField(related_name='manifest_labels', to='app.label')),
                ('summary', models.ManyToManyField(related_name='manifest_summaries', to='app.label')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ManyToManyField(related_name='metadata_labels', to='app.label')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='app.manifest')),
                ('value', models.ManyToManyField(related_name='metadata_values', to='app.label')),
            ],
        ),
    ]
