# Generated by Django 5.0.7 on 2024-07-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fotografia', 'Fotografia'), ('pintura', 'Pintura'), ('manuscrito', 'Manuscrito'), ('outro', 'Outro')], default='fotografia', max_length=50)),
                ('formato', models.CharField(choices=[('jpeg', 'JPEG'), ('tiff', 'TIFF'), ('png', 'PNG')], default='tiff', max_length=50)),
                ('arquivo_imagem', models.ImageField(upload_to='data/images')),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('largura', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaginaAnotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.JSONField()),
                ('largura', models.IntegerField()),
                ('altura', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tela',
                'verbose_name_plural': 'Telas',
            },
        ),
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('rotulo', models.JSONField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('comment', 'Comentário'), ('describing', 'Descrição'), ('highlighting', 'Destaque'), ('scanning', 'Digitalização')], default='comment', max_length=50)),
                ('x', models.IntegerField(help_text='Coordenada X do canto superior esquerdo')),
                ('y', models.IntegerField(help_text='Coordenada Y do canto superior esquerdo')),
                ('largura', models.IntegerField(help_text='Largura da área anotada')),
                ('altura', models.IntegerField(help_text='Altura da área anotada')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imagem')),
                ('pagina_anotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='app.paginaanotacao')),
            ],
        ),
        migrations.AddField(
            model_name='paginaanotacao',
            name='tela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas_anotacoes', to='app.tela'),
        ),
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Manifest', max_length=50)),
                ('rotulo', models.JSONField()),
                ('resumo', models.JSONField(blank=True, null=True)),
                ('metadados', models.JSONField(blank=True, help_text='Metadados adicionais em formato JSON', null=True)),
                ('itens', models.ManyToManyField(blank=True, related_name='manifestos', to='app.tela')),
            ],
        ),
    ]
