# Generated by Django 5.0.7 on 2024-07-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvas',
            options={'verbose_name_plural': 'Canvases'},
        ),
        migrations.AlterUniqueTogether(
            name='canvas',
            unique_together={('height', 'width')},
        ),
    ]
