# Generated by Django 5.0.7 on 2024-07-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_canvas_options_alter_canvas_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
