# Generated by Django 5.0.7 on 2024-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='value',
            field=models.TextField(),
        ),
    ]
