# Generated by Django 5.0.7 on 2024-07-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_anotacao_visualizacao_remove_colecao_itens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='tipo',
        ),
    ]
