# Generated by Django 5.0.7 on 2024-10-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_label_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
