# Generated by Django 5.0.7 on 2024-07-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_manifest_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='canvas',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='metadata',
            name='items',
            field=models.ManyToManyField(related_name='manifests', to='app.canvas'),
        ),
    ]
