# Generated by Django 5.0.7 on 2024-07-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_objeto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='imagem_arquivo',
            field=models.ImageField(blank=True, null=True, upload_to='data/images'),
        ),
    ]
