# Generated by Django 5.0.7 on 2024-07-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_canvas_unique_together_metadata_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationpage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='items',
        ),
        migrations.AddField(
            model_name='manifest',
            name='items',
            field=models.ManyToManyField(related_name='manifests', to='app.canvas'),
        ),
        migrations.AlterField(
            model_name='annotationpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
